version: "3"

volumes:
  local_production_postgres_data: {}
  local_production_postgres_data_backups: {}
  local_production_traefik: {}
  local_production_django_media: {}
 
services:
  django:{% if cookiecutter.use_celery == 'y' %} &django{% endif %}
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: {{ cookiecutter.project_slug }}_local_production_django
    volumes:
      - local_production_django_media:/app/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/backend/.django
      - ./.envs/.production/backend/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_production_postgres
    volumes:
      - local_production_postgres_data:/var/lib/postgresql/data
      - local_production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/backend/.postgres

  redis:
    image: redis:6
    
  {%- if cookiecutter.use_celery == 'y' %}
  
  celeryworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_production_flower
    command: /start-flower
  {%- endif %}
  
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_production_nginx
    depends_on:
      - django
    volumes:
      - local_production_django_media:/usr/share/nginx/media:ro
      
  nextjs:
    build:
      context: .
      dockerfile: ./compose/production/next/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_production_nextjs
    env_file:
      - ./.envs/.production/frontend/.next

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik-http/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_production_traefik
    depends_on:
      - django
    volumes:
      - local_production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      {%- if cookiecutter.use_celery == 'y' %}
      - "0.0.0.0:5555:5555"
      {%- endif %}